version: '3.9'
services:
  users_db_m3br:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
      - group-project:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d
  web:
    image: node:lts
    user: 'root'
    working_dir: /repository
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - users_db_m3br
    ports:
      - '3000:3000'
    volumes:
      - ./:/repository
    command: 'npm run testandrun' #TODO: change the command to `npm run testandrun` to run mocha or 'npm start' conversly
  bg:
    image: node:lts
    user: 'root'
    working_dir: /repository
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - users_db_m3br
    volumes:
      - ./:/repository
    command: 'npm run timer' #npm run timer 
volumes:
  group-project: